export const CACHE_SEARCH = 'CACHED_SEARCH';
export const SEND_ENTITIES = 'SEND_ENTITIES';
export const SEND_ARTICLES = 'SEND_ARTICLES';
export const RESET_CACHED_ARTICLES = 'RESET_CACHED_ARTICLES';
export const RESET_ENTITIES = 'RESET_ENTITIES';
export const NO_RESULTS = 'NO_RESULTS';

export const AUTH_USER = 'AUTH_USER';
